name = "phase5-coord"
type = "javascript"
account_id = "70ae910ed6cd4d89a96a15594136a620"
workers_dev = true
compatibility_date = "2024-01-01"

[env.production]
name = "phase5-coord-prod"

[[env.production.kv_namespaces]]
binding = "KV"
id = "kv-phase5-namespace"
preview_id = "kv-phase5-namespace"

[build]
command = ""
cwd = ""
