name = "phase2-coord"
type = "javascript"
account_id = "e899c154113887c373fef4dc6ac63930"
workers_dev = true
compatibility_date = "2024-01-01"

[env.production]
name = "phase2-coord-prod"

[[env.production.kv_namespaces]]
binding = "KV"
id = "kv-phase2-namespace"
preview_id = "kv-phase2-namespace"

[build]
command = ""
cwd = ""
