name = "phase1-coord"
type = "javascript"
account_id = "7b2347dce656e4f0959b2e20a9bafee3"
workers_dev = true
compatibility_date = "2024-01-01"

[env.production]
name = "phase1-coord-prod"

[[env.production.kv_namespaces]]
binding = "KV"
id = "kv-phase1-namespace"
preview_id = "kv-phase1-namespace"

[build]
command = ""
cwd = ""
