name = "phase6-coord"
type = "javascript"
account_id = "f42361289b500df1a522493067604d2c"
workers_dev = true
compatibility_date = "2024-01-01"

[env.production]
name = "phase6-coord-prod"

[[env.production.kv_namespaces]]
binding = "KV"
id = "kv-phase6-namespace"
preview_id = "kv-phase6-namespace"

[build]
command = ""
cwd = ""
