name = "phase4-coord"
type = "javascript"
account_id = "035924f9812920fff6b70adf2904d581"
workers_dev = true
compatibility_date = "2024-01-01"

[env.production]
name = "phase4-coord-prod"

[[env.production.kv_namespaces]]
binding = "KV"
id = "kv-phase4-namespace"
preview_id = "kv-phase4-namespace"

[build]
command = ""
cwd = ""
